### ISSUE TITLE
Error: no OccuType

### ISSUE THREAD

**Issue by cefect** [FloodRiskGroup/floodrisk2#2]
Having the same issue described here:

https://github.com/FloodRiskGroup/floodrisk/issues/5

Problem arises when using any 'Economic Tangible' 'Exposure' layers from the example 'FloodRiskData_2'. I tried loading the 'GeoDB_Floodrisk_2_template.sqlite', the 'Geodatabase.Sqlite' from the example files, and creating a new one. All seemed to have a layer 'StructurePoly' with these fields:

OBJECTID | instance | OccuType | Valstr | Valcon | Shape_Length | Shape_Area

while the sample 'PropertyPoly.shp' has these fields:

OccuType Valstr Valcon Descr Shape_Area

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
QGIS version: 3.8.3-Zanzibar Zanzibar, 685d8b15d2

**Comment by FloodRiskGroup** [comment]
The problem does not depend on the data as the missing fields in the shape file are automatically compiled by the plugin.
The problem instead depends on the fact that some installations of gdal do not support the query "SELECT DISTINCT ..." on a shapefile.
To avoid this problem, the LoadGeodatiFloodRisk.py module has been modified.
The new version of the module is already on github and soon the floodrisk2 plugin will also be updated.
