### ISSUE TITLE
Numpy error while computing loss of life

### ISSUE THREAD

**Issue by danieluct** [FloodRiskGroup/floodrisk2#3]
I obtain the following error when attempting to run the simulation in the loss of life scenario:
`TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.`
The error happens at https://github.com/FloodRiskGroup/floodrisk2/blob/d02aa6380998cd6b6e0c3dcef5eba94dfd49833d/ProjectCalcolaRischio/CalcolaScenarioRischio.py#L770

The respective array is declared as boolean, and indeed subtraction does not make sense. Is there an overload for minus in a specific version of Python, or is just a coding error? I notice that a similar code sequence in the Direct Economic Damages scenarios makes an explicit cast to int: https://github.com/FloodRiskGroup/floodrisk2/blob/d02aa6380998cd6b6e0c3dcef5eba94dfd49833d/ProjectCalcolaDanno/CalcolaScenarioDanno.py#L267
Is it safe to replicate the cast, or it would affect the current algorithm?

**Comment by FloodRiskGroup** [comment]
Arrays declared as boolean are arrays with a value of 0 to mean false and 1 to mean true.
In previous versions of python their subtraction was not reported as an error.
Now to avoid the error messag I made the change by declaring the array as an integer.

**Comment by danieluct** [comment]
Thank you, it is working now.
